#!/usr/bin/env bash
# Writes .env.dev, the env file for the LOCAL Supabase stack (docs/LOCAL_DEV.md),
# from `supabase status` plus freshly generated secrets. Never touches .env,
# which points at the hosted database that production shares.
set -euo pipefail

cd "$(dirname "$0")/../.."
target=.env.dev

if [[ -e "$target" && "${1:-}" != "--force" ]]; then
  echo "$target already exists; pass --force to regenerate it (new JWT secrets sign everyone out)." >&2
  exit 1
fi

if ! status=$(supabase status -o env 2>/dev/null); then
  echo "The local stack is not running. Start Docker Desktop, then: pnpm db:local:start" >&2
  exit 1
fi

# `supabase status -o env` prints KEY="value" lines.
read_status() { sed -n "s/^$1=\"\{0,1\}\([^\"]*\)\"\{0,1\}$/\1/p" <<<"$status"; }
api_url=$(read_status API_URL)
db_url=$(read_status DB_URL)
service_role_key=$(read_status SERVICE_ROLE_KEY)

if [[ -z "$api_url" || -z "$db_url" || -z "$service_role_key" ]]; then
  echo "Could not read API_URL, DB_URL and SERVICE_ROLE_KEY from 'supabase status -o env'." >&2
  exit 1
fi

# The file holds secrets: owner-only. umask covers a new file; chmod covers
# --force, where `cat >` keeps an existing file's mode.
umask 077
cat >"$target" <<EOF
# LOCAL Supabase stack only. Generated by scripts/dev/init-env.sh; see docs/LOCAL_DEV.md.
# Every URL here must stay on this machine: the dev scripts refuse to run otherwise.

DATABASE_URL=$db_url
DIRECT_URL=$db_url
NUXT_SUPABASE_URL=$api_url
NUXT_SUPABASE_SERVICE_ROLE_KEY=$service_role_key

NUXT_SESSION_PASSWORD=$(openssl rand -hex 32)
NUXT_JWT_ACCESS_SECRET=$(openssl rand -hex 48)
NUXT_JWT_REFRESH_SECRET=$(openssl rand -hex 48)
NUXT_JWT_REFRESH_ROTATION=true

# Lets you trigger the reminder sweep by hand (docs/LOCAL_DEV.md).
NUXT_NOTIFICATIONS_CRON_SECRET=local-sweep-secret

# Native Apple/Google sign-in against the local stack: copy these two from .env
# if you want them. Email sign-in needs neither.
NUXT_APPLE_BUNDLE_ID=
NUXT_GOOGLE_IOS_CLIENT_ID=

# Deliberately empty locally: no APNs pushes, no rate limiting, no Sentry, no
# web OAuth, no CORS origin.
EOF
chmod 600 "$target"

echo "Wrote $target"
